# Generated by Django 4.2.7 on 2024-03-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.ManyToManyField(to='mainApp.size', verbose_name='Размеры'),
        ),
    ]
