# Generated by Django 4.2.7 on 2023-12-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug_name',
            field=models.CharField(default='slug_name', max_length=100),
        ),
    ]
