# Generated by Django 4.2.7 on 2024-03-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_size_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='quantity',
        ),
    ]
