# Generated by Django 4.2.7 on 2023-12-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_category_slug_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug_name',
            field=models.CharField(default='slug_name', max_length=100),
        ),
    ]
