# Generated by Django 4.2.7 on 2024-01-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_alter_item_description_alter_item_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='item',
            name='item_slug',
            field=models.CharField(default='item_slug', max_length=100, verbose_name='Слаг (предмета)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug_name',
            field=models.CharField(default='slug_name', max_length=100, verbose_name='Слаг (форен кей)'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='comment',
            field=models.TextField(max_length=255, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(max_length=255, verbose_name='Рейтинг'),
        ),
    ]
