# Generated by Django 4.2.7 on 2024-02-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_alter_reviews_options_item_item_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Скидка'),
        ),
    ]
