# Generated by Django 4.2.7 on 2024-03-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreement',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Соглашение'),
        ),
    ]
