# Generated by Django 4.2.7 on 2024-03-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Проданый товар', 'verbose_name_plural': 'Проданые товары'},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.IntegerField(default=0, verbose_name='Размер'),
        ),
    ]
